### ISSUE TITLE
Simplified class instanciation

### ISSUE THREAD

**Issue by blatinier** [blatinier/pyhunspell#18]
Currently instanciation needs two parameters:
- Full path to .dic
- Full path to .aff

The idea is to provide some easier way to instanciate HunSpell:
- No arguments → get the en_US dic and aff in standard paths.
- `dict_name` keyword argument → get the `dict_name.dic` and `dict_name.aff` in standard paths.

**Comment by PanderMusubi** [comment]
And as a third option, when path to dict is given, use that for path to aff file.

**Comment by blatinier** [comment]
Good idea, I add it to the things to do.

**Comment by louis-langholtz** [comment]
Will this also support the use of a personal dictionary as `hunspell -p dict` does? I'd love that capability! Thanks!

**Comment by blatinier** [comment]
Isn't it the same as option 3? You give the path to your .dic file (anywhere and any .dic file) and the .aff file is search in the same location.
And it's currently already available if you give your .dic and .aff path. Or did I missunderstood something?

**Comment by blatinier** [comment]
I checked -p option and it's already available now since you must provide full path to the dic and aff files.

**Comment by louis-langholtz** [comment]
Thank you for responding.

Assuming that option 3 is:

> Given a path to the dic, use it for the aff.

I don't know if I'm asking about the same capability. The need for the `.aff` file (an affix file?) is unclear to me. `hunspell` seems to expect/require that a `.aff` file exists in some uses but not with the `-p` flag usage.

When I use hunspell with a personal dictionary specified via the command line, I'm just specifying a `.dic` file directly as in `hunspell -p Documentation/extra-words.dic`. There's no `.aff` file in that same folder but hunspell indeed uses the extra words file in its spell checking. That's the behavior I'm looking for &mdash; the ability to add extra words as acceptable spellings without a need to add any other kind of configuration file.

I'll open a new issue about a different problem which is adding to the confusion for me.

**Comment by blatinier** [comment]
Ok the -p option adds list of word to the default dict. This is already available through the `add_dic` method. In fact hunspell invoked alone search the env vars to fetch the dic corresponding to $LANG (more or less, it's a bit more complicated, see `man hunspell`). So when you do `hunspell -p extra.dic` it can be translated to:

    h = HunSpell('path/to/file.dic', 'path/to/file.aff')
    h.add_dic('extra.dic')

I hope this answer your questions (ok #43 too :) )

**Comment by louis-langholtz** [comment]
This looks helpful. Thank you!

A problem though that I'm running into that relates to what's been suggested is not knowing where hunspell is actually getting its default `.dic` and `.aff` files from. So at the moment, I haven't yet been able to instantiate the class since it doesn't appear to support the no argument construction yet:

```
>>> import hunspell
>>> h = HunSpell()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'HunSpell' is not defined
>>> h = hunspell.HunSpell()
TypeError: function takes exactly 2 arguments (0 given)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'HunSpell'> returned a result with an error set
>>> 
```

**Comment by blatinier** [comment]
Yes, the constructor fails at failing properly :)
When I took over the package it was a Segfault and when I stop working on it when the Segfault was gone, but this is a problem too (I edit the first message here to add it to the scope of this issue).

**Comment by jirib** [comment]
In `hunspell` CLI one doesn't need to put path, see:

```
$ hunspell -D
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/usr/share/mozilla-dicts:/home/jiri/.config/libreoffice/4/user/wordbook:/usr/lib/libreoffice/share/wordbook
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
./cs_CZ
./de_DE_frami
./fr
./it_IT
/home/jiri/.config/libreoffice/4/user/wordbook/fr
/home/jiri/.config/libreoffice/4/user/wordbook/cs_CZ
/home/jiri/.config/libreoffice/4/user/wordbook/it_IT
/home/jiri/.config/libreoffice/4/user/wordbook/de_DE_frami
/home/jiri/.config/libreoffice/4/user/wordbook/en_US
/home/jiri/.config/libreoffice/4/user/wordbook/cs_CZ_CC0
/usr/lib/libreoffice/share/wordbook/en-US
/usr/lib/libreoffice/share/wordbook/hu_AkH11
/usr/lib/libreoffice/share/wordbook/technical
/usr/lib/libreoffice/share/wordbook/sl
/usr/lib/libreoffice/share/wordbook/en-GB
```

**Comment by blatinier** [comment]
Yep but this package doesn't rely on the hunspell cli. It relies on the libhunspell (which the hunspell cli probably wraps…)
The purpose of this issue is to allow such a behavior.
