### ISSUE TITLE
Cannot install on Python 3.7.3

### ISSUE THREAD

**Issue by shashwatmath** [blatinier/pyhunspell#65]
Hi,

I cannot install the hunspell library on Python 3.7.3
It gives following error while 'pip install hunspell'

    ERROR: Complete output from command 'c:\program files (x86)\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\shashwat.math\\AppData\\Local\\Temp\\pip-install-3ul6rkq_\\hunspell\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shashwat.math\AppData\Local\Temp\pip-record-hsp6wr0z\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'hunspell' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHUNSPELL_STATIC -IV:/hunspell-1.3.3/src/hunspell "-Ic:\program files (x86)\python37-32\include" "-Ic:\program files (x86)\python37-32\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tphunspell.cpp /Fobuild\temp.win32-3.7\Release\hunspell.obj /MT
    cl : Command line warning D9025 : overriding '/MD' with '/MT'
    hunspell.cpp
    hunspell.cpp(20): fatal error C1083: Cannot open include file: 'hunspell.hxx': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command "'c:\program files (x86)\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\shashwat.math\\AppData\\Local\\Temp\\pip-install-3ul6rkq_\\hunspell\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shashwat.math\AppData\Local\Temp\pip-record-hsp6wr0z\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\shashwat.math\AppData\Local\Temp\pip-install-3ul6rkq_\hunspell\

**Comment by blatinier** [comment]
You appear to use windows. 
Here is an old compiled version https://pyhunspell.latinier.fr/
It's the best I have for now.

**Comment by matejbadin** [comment]
Unfortunately, this does not help much
> >>> import hunspell
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: DLL load failed: The specified module could not be found.
> >>>

**Comment by matejbadin** [comment]
Unfortunately, this does not help much. 

```
import hunspell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by blatinier** [comment]
The message indicates that you lack the dll for hunspell. 
pyhunspell is just a binding between python and hunspell. You need to get hunspell before using pyhunspell on your computer

**Comment by matejbadin** [comment]
I have downloaded hunspell and it is in PATH (exe), but where should I include DLL? Or where can one see from where does Python include DLL by default?

**Comment by RishabhMech** [comment]
> I have downloaded hunspell and it is in PATH (exe), but where should I include DLL? Or where can one see from where does Python include DLL by default?

Hi matejbadin! Did your hunspell work yet?
